title: "Anne Lammar - MSTAT, RCST"
description: "Anne Lammar therapist"
author: "Hugh Carroll"
baseurl: "/"
url: "https://annelammar.com"
permalink: /:path/:basename:output_ext

markdown: kramdown
highlighter: rouge

plugins: [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - changelog.md
    - "*.Rmd"
    - notes.txt
