theme = "chalk"
baseURL = 'https://annelammar.com'
languageCode = 'en-us'
title = 'Anne Lammar'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.chalk]
blog_theme = "light"
about_enabled = true
theme_toggle = true
scrollappear_enabled = true
