# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Regular Clinics', folder: 'pages', file: 'regular-clinics.html'}
- {name: 'Contact Details', folder: 'pages', file: 'contact-details.html'}
- {name: 'Alexander Technique', folder: 'pages', file: 'alexander-technique.html'}
- {name: 'Craniosacral Therapy', folder: 'pages', file: 'craniosacral.html'}
- {name: 'Prenatal & Birth Therapy', folder: 'pages', file: 'birth.html'}
- {name: 'Doula (birth helper)', folder: 'pages', file: 'doula.html'}
- {name: 'Links', folder: 'pages', file: 'links.html'}
- {name: 'About Anne', folder: 'pages', file: 'about.html'}
- {name: 'Articles & Inspiration', folder: 'pages', file: 'articles.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
#social:
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: ''
  previous_page: ''

sharing_button_prompt: 'share'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
